In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [7]:
df=pd.read_csv("E:\\22UCS085\\E03 linear regression multiple variable\\Exercise\\hiring.csv")
df

experience  testscore  interviewscore  salary
0           4          8               9   50000
1           5          8               6   45000
2           5          6               7   60000
3           2         10              10   65000
4           7          9               6   70000
5           3          7              10   62000
6          10          7               7   72000
7          11          7               8   80000

In [10]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','testscore','interviewscore']],df.salary)

LinearRegression()

In [11]:
reg.predict([[2,9,6]])

array([44789.96499417])

In [12]:
reg.coef_

array([3579.92998833, 1943.40723454, 3609.10151692])

In [13]:
reg.intercept_

-1515.1691948658045

In [14]:
2*3579.92998833+9*1943.40723454+6*3609.10151692 -1515.1691948658045

44789.964994174195

In [15]:
reg.predict([[12,10,10]])

array([96969.0781797])

In [16]:
reg.coef_

array([3579.92998833, 1943.40723454, 3609.10151692])

In [17]:
reg.intercept_

-1515.1691948658045

In [18]:
12*3579.92998833+10*1943.40723454+10*3609.10151692 -1515.1691948658045

96969.07817969419